[general]
import = [ "~/.config/alacritty/gruvbox_dark.toml" ]

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 1
blur = false

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }
size = 16

[cursor]
style = { shape = "Block", blinking = "Always" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[keyboard]
bindings = [
  { key = "V", mods = "Control | Shift", mode = "~Search", action = "ToggleViMode" },
  { key = "Return", mods = "Shift", chars = "\u001b\r" }
]
